### ISSUE TITLE
Doesn't work with prototype extensions off

### ISSUE THREAD

**Issue by vlascik** [xomaczar/ember-cli-ion-rangeslider#10]
If you have Ember function prototype extensions turned off (I think it's discouraged a lot now), .on is not a function and this addon fails:
```
"TypeError: (intermediate value)(intermediate value).on is not a function
    at Module.callback (http://localhost:4200/assets/vendor.js:218684:8)
    at Module.exports (http://localhost:4200/assets/vendor.js:132:32)
....
```
This should be rewritten in mixin: (`_startObserving`, `_stopObserving`) and in addon  (`didInsertElement` and `willDestroyElement`).

https://guides.emberjs.com/v2.3.0/configuring-ember/disabling-prototype-extensions/

**Comment by cursedquail** [comment]
Hi @vlascik, it looks like this addon is no longer maintained. You should go check out my fork over at #9 . I've made several fixes over there that I think you should check out! If you have any questions feel free to raise an issue.
